site_name: lightkube-models
theme:
  name: material
  hljs_style: monokai
  palette:
    primary: deep purple

repo_name: gtsystem/lightkube-models
repo_url: https://github.com/gtsystem/lightkube-models
edit_uri: ""

extra_css:
  - css/custom.css

markdown_extensions:
  - lightkube-generate.mkextension:ModelLinkExtension
  - lightkube-generate.mkextension:K8SLinkExtension
  - admonition
  - mkautodoc
  - codehilite
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - markdown_include.include:
      base_path: .
